"use client";

import { useState } from "react";
import { ArrowRight, AtSign, BriefcaseBusiness, CheckCircle2, Code2, Copy, Send, Sparkles } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { ReddyHoverAction } from "@/components/portfolio-ask";
import { TallyForm } from "@/components/tally-form";

const fromCodes = (values: number[]) => String.fromCharCode(...values);
const contactAddress = () => `${fromCodes([108,111,107,101,115,104,114,118,101,101,114,97,98,104,97,100,114,97])}@${fromCodes([103,109,97,105,108])}.${fromCodes([99,111,109])}`;
const profileAddress = () => `${fromCodes([104,116,116,112,115,58,47,47,119,119,119,46,108,105,110,107,101,100,105,110,46,99,111,109,47,105,110,47])}${fromCodes([108,48,107,51,53,104,114,51,100,100,121,45,100,51,118])}/`;
const intents = [{ name:"Hiring", detail:"Role fit, interview topics, or resume follow-up.", icon:BriefcaseBusiness, subject:"A role where production GenAI needs evidence" },{ name:"Technical collaboration", detail:"Architecture reviews, GenAI systems, or build ideas.", icon:Code2, subject:"A production GenAI system worth thinking through" },{ name:"AI engineering discussion", detail:"RAG, agents, LLM security, or evaluation.", icon:Sparkles, subject:"A conversation about reliable AI systems" }] as const;

export default function ContactPage(){
  const [intent,setIntent]=useState("Hiring"); const selected=intents.find(item=>item.name===intent) ?? intents[0]; const [context,setContext]=useState("");
  const subject=encodeURIComponent(`${intent}: ${selected.subject}`); const body=encodeURIComponent(context.trim()?`Hi Lokesh,\n\nI’m reaching out about ${intent.toLowerCase()}.\n\n${context.trim()}\n\nBest,`:`Hi Lokesh,\n\nI’d like to start a conversation about ${intent.toLowerCase()}.\n\nBest,`);
  const openEmail=()=>{window.location.href=`mailto:${contactAddress()}?subject=${subject}&body=${body}`}; const openProfile=()=>{window.open(profileAddress(),"_blank","noopener,noreferrer")}; const copyAddress=()=>{void navigator.clipboard?.writeText(contactAddress())};
  return <main><PageHeading eyebrow="CONTACT / OPEN CHANNEL" title="Bring the problem. Leave with a next step." intro="A good first message does not need to be long. Choose the kind of conversation, add the context that matters, and continue in your own email client."/>
    <section className="shell contact-flow"><div className="contact-stepper"><span className="active"><b>01</b>Choose intent</span><i/><span><b>02</b>Add context</span><i/><span><b>03</b>Continue privately</span></div><div className="contact-grid contact-grid-refined"><div className="contact-left-stack"><div className="contact-panel contact-intent-panel"><p className="kicker">WHAT SHOULD THIS CONVERSATION DO?</p><h2>Point the message at the right door.</h2><div className="intent-grid contact-intents">{intents.map(({name,detail,icon:Icon})=><button key={name} type="button" className={intent===name?"selected":""} onClick={()=>setIntent(name)}><Icon size={19}/><span><strong>{name}</strong><small>{detail}</small></span><ArrowRight size={16}/></button>)}</div></div><div className="contact-panel contact-context-panel"><div className="contact-context-head"><div><p className="kicker">OPTIONAL CONTEXT BUILDER</p><h2>What are you working on?</h2></div><span className="contact-private">PRIVATE BY DEFAULT</span></div><p className="contact-context-copy">Give one or two sentences. This text stays in your browser until you choose to open your email app.</p><textarea value={context} onChange={e=>setContext(e.target.value)} placeholder="I’m building a compliance assistant and want to compare retrieval and evaluation approaches…"/><div className="contact-context-footer"><span>{context.length}/600 · never stored here</span><button className="button" type="button" onClick={openEmail}><Send size={16}/> Open prepared email <ArrowRight size={15}/></button></div></div></div><TallyForm /></div></section>
    <section className="shell contact-proof-grid"><article><span className="kicker">THE HANDOFF</span><h3>Your context becomes a useful subject and opening.</h3><p>Instead of a blank email, the selected intent and your own words travel with you. You stay in control of what gets sent.</p></article><article><span className="kicker">PRIVATE DIRECT CHANNEL</span><h3>Reach Lokesh directly</h3><p>The address stays hidden from page scrapers until you explicitly choose to copy it.</p><button className="text-link" type="button" onClick={copyAddress}><Copy size={15}/> Copy email address</button></article><article><span className="kicker">OTHER ROUTE</span><h3>Prefer a profile-first conversation?</h3><button className="text-link" type="button" onClick={openProfile}><AtSign size={15}/> Open LinkedIn <ArrowRight size={14}/></button></article></section>
    <section className="shell contact-next"><div><p className="kicker">WHAT HAPPENS NEXT</p><h2>Clear context. Direct response. No form funnel.</h2><ReddyHoverAction scope="contact and collaboration" question="Explain what makes a strong first message to Lokesh and suggest what context to include." /></div><div className="contact-next-list"><div><CheckCircle2/><span><strong>Context first</strong><small>Your selected topic guides the opening.</small></span></div><div><CheckCircle2/><span><strong>Private handoff</strong><small>Your email client owns the final send.</small></span></div><div><CheckCircle2/><span><strong>Useful reply</strong><small>Technical conversations can start at the right altitude.</small></span></div></div></section>
  </main>
}
