export const nav = [
  ["Projects", "/projects"], ["Architecture", "/architecture"], ["Security", "/security"],
  ["Experience", "/experience"], ["Studio", "/studio"], ["Playground", "/playground"], ["About", "/about"], ["Lab", "/lab/rag-debugger"],
] as const;

export const projects = [
  {
    slug: "regulatory-intelligence-platform",
    title: "Regulated Financial Services Intelligence Platform",
    label: "RAG · Compliance · Guardrails",
    evidence: "Professional experience · public-safe summary",
    role: "RAG architecture, agent workflows, evaluation, and security controls",
    scope: "A regulated-document intelligence platform for grounded research, policy Q&A, change analysis, and compliance workflows. Client-specific documents and internal controls are intentionally summarized.",
    summary: "A retrieval-augmented platform combining semantic chunking, metadata filtering, hybrid retrieval, reranking, grounded generation, source attribution, validation, and review gates.",
    outcome: "Reduced regulatory research time from 45+ minutes to under 4 minutes per query in the documented workflow.",
    stack: ["Azure OpenAI", "LangGraph", "Pinecone", "Azure AI Search", "FastAPI", "RAGAS"],
    metrics: [["45+ → <4", "minutes per query"], ["300", "golden QA questions"], ["0", "production incidents reported"]],
    problem: "Regulated knowledge is large, fragmented, access-sensitive, and costly to search manually. The system needed grounded answers, scoped retrieval, traceability, and review before distribution.",
    decisions: ["Hybrid retrieval and cross-encoder reranking", "Access-aware document filtering", "Structured outputs with validation loops", "CI/CD evaluation gates and human review"],
    failure: "Weak terminology alignment can reduce recall. Domain metadata, query expansion, and evaluation slices make that failure observable and recoverable.",
  },
  {
    slug: "audit-intelligence-platform",
    title: "Professional Services Audit Intelligence Platform",
    label: "RAG · Audit Intelligence · Agents",
    evidence: "Professional experience · public-safe summary",
    role: "Agentic workflow design, retrieval, anomaly detection, evaluation, and delivery",
    scope: "An audit intelligence workflow for evidence gathering, workpaper linkage, risk flagging, anomaly detection, and grounded standards research. Internal client documents are not exposed.",
    summary: "A retrieval-backed audit assistant with engagement-scoped retrieval, evidence-grounded answers, ranked risk signals, mandatory reviewer approval, and measurable quality gates.",
    outcome: "Reduced manual document-review effort by 34% and reduced evidence-search time from about 40 minutes to under 4 minutes per assertion.",
    stack: ["Azure OpenAI", "LangGraph", "Pinecone", "FastAPI", "RAGAS", "Azure AI Search"],
    metrics: [["34%", "less manual review"], ["<4 min", "evidence search"], ["28%", "less initial analysis time"]],
    problem: "Audit teams need fast evidence discovery without weakening independence, confidentiality, review hierarchy, or traceability.",
    decisions: ["Engagement-scoped indexes", "Human review before client-facing output", "Evidence-aware anomaly ranking", "Immutable audit events and redaction"],
    failure: "Cross-engagement retrieval and unsupported standards references were treated as release-blocking risks through scoped indexes and evaluation gates.",
  },
  {
    slug: "deal-advisory-due-diligence",
    title: "Deal Advisory Due Diligence Agent",
    label: "Agents · Document Intelligence · Risk",
    evidence: "Professional experience · public-safe summary",
    role: "LangGraph orchestration, document extraction, risk scoring, and review controls",
    scope: "A multi-document workflow that classifies financial and transaction documents, extracts structured findings, checks consistency, and produces reviewer-ready summaries.",
    summary: "A six-step agentic pipeline from document classification through extraction, entity resolution, risk scoring, consistency checks, and structured deal-memo generation.",
    outcome: "Reduced first-pass due-diligence summary turnaround from 5 business days to 1.5 days across 14 pilot engagements.",
    stack: ["LangGraph", "GPT-4o", "LlamaIndex", "Pinecone", "FastAPI", "Azure"],
    metrics: [["5 → 1.5", "business days"], ["14", "pilot engagements"], ["23", "discrepancies surfaced"]],
    problem: "Transaction review spans heterogeneous documents and requires consistent findings, cross-document checks, and senior approval.",
    decisions: ["Explicit six-step state graph", "Structured risk severity", "Cross-document consistency checks", "Partner-level review gate"],
    failure: "A fluent summary can hide an inconsistency. The workflow therefore checks entities and claims across documents before generating the final structure.",
  },
  {
    slug: "llm-evaluation-quality-gates",
    title: "LLM Evaluation & Quality Gate Framework",
    label: "Evaluation · CI/CD · Observability",
    evidence: "Professional experience · public-safe summary",
    role: "Evaluation harness design, CI/CD integration, dashboards, and release policy",
    scope: "A modular evaluation harness covering retrieval, generation, classification, policy adherence, prompt changes, and index updates before release.",
    summary: "Automated quality gates with per-metric reports, model and prompt version tracking, and dashboards for regression diagnosis.",
    outcome: "Reduced post-deployment production regressions by 67% over a 12-month measurement window.",
    stack: ["RAGAS", "DeepEval", "Python", "GitHub Actions", "Azure", "Grafana"],
    metrics: [["200+", "curated test cases"], ["87%", "flow coverage"], ["67%", "fewer regressions"]],
    problem: "LLM quality can regress silently across retrieval, prompts, models, and indexes. Releases need repeatable evidence rather than one aggregate score.",
    decisions: ["Per-PR threshold gates", "Retrieval and generation metrics separated", "Versioned metric trajectories", "Block merges on critical failures"],
    failure: "Prompt-template drift caused silent standards-mapping regressions; trajectory dashboards exposed the change before user-facing impact.",
  },
  {
    slug: "domain-adapted-llama3",
    title: "Domain-Adapted Llama 3",
    label: "Fine-tuning · MLOps · Cost Control",
    evidence: "Professional experience · public-safe summary",
    role: "Dataset curation, QLoRA fine-tuning, evaluation, serving, and rollback",
    scope: "A domain-adapted model workflow for classification and standards-lookup tasks with reproducible training, staged promotion, and evaluation gates.",
    summary: "QLoRA fine-tuning, MLflow experiment tracking, vLLM serving, and staged promotion with quality checks at each gate.",
    outcome: "Improved task F1 from 0.74 to 0.91 and reduced per-query inference cost by 38%.",
    stack: ["Llama 3 8B", "QLoRA", "MLflow", "vLLM", "Azure", "Python"],
    metrics: [["0.74 → 0.91", "task F1"], ["38%", "lower cost"], ["34", "tracked runs"]],
    problem: "High-volume domain tasks need strong quality and lower unit cost without sacrificing reproducibility or rollback.",
    decisions: ["Parameter-efficient QLoRA adaptation", "Dataset and hyperparameter versioning", "Canary promotion", "Evaluation-gated rollback"],
    failure: "Fine-tuning gains are task-specific; model promotion stayed gated by domain evaluation rather than benchmark performance alone.",
  },
  {
    slug: "infraspeak",
    title: "InfraSpeak — Network Infrastructure Provisioning",
    label: "IaC · Tool Use · Policy",
    evidence: "Professional experience · public-safe summary",
    role: "Natural-language provisioning, policy validation, and controlled execution",
    scope: "A natural-language interface that converts infrastructure intent into validated Terraform and Ansible configuration with mandatory engineer approval.",
    summary: "A three-stage pipeline from structured intent to allowlist checks to configuration generation, with secrets masking and policy controls.",
    outcome: "Cut infrastructure provisioning cycle time by 60% and manual template errors by 74%.",
    stack: ["GPT-3", "Azure OpenAI", "FastAPI", "FAISS", "Terraform", "Ansible"],
    metrics: [["60%", "faster provisioning"], ["74%", "fewer template errors"], ["0", "credential exposures reported"]],
    problem: "Plain-English infrastructure requests must become consistent, policy-compliant configurations without allowing uncontrolled production changes.",
    decisions: ["Intent before generation", "Topology allowlist checks", "Secrets masking", "Mandatory network-engineer approval"],
    failure: "Domain-specific telecom vocabulary caused intent errors; a retrieval-backed glossary reduced ambiguity before configuration generation.",
  },
  {
    slug: "engineering-knowledge-assistant",
    title: "Engineering Knowledge Assistant",
    label: "RAG · Developer Experience · Search",
    evidence: "Professional experience · public-safe summary",
    role: "Knowledge retrieval, metadata filtering, source-aware response design",
    scope: "A retrieval-backed assistant over engineering runbooks, architecture records, rollout planning, and incident history.",
    summary: "Hybrid keyword and dense retrieval with metadata filters scoped answers to the right technology domain and business unit.",
    outcome: "Improved first-contact resolution by 41% and reduced time to find operational guidance from 18 minutes to under 90 seconds.",
    stack: ["GPT-3", "Azure OpenAI", "FAISS", "Weaviate", "FastAPI", "Python"],
    metrics: [["8,000+", "indexed pages"], ["41%", "better resolution"], ["<90 sec", "guidance search"]],
    problem: "Large operational knowledge bases need fast, scoped answers without cross-domain confusion or unsupported context.",
    decisions: ["Hybrid keyword and dense retrieval", "Technology and unit metadata filters", "Source-aware answers", "Knowledge layer reused for policy checks"],
    failure: "A single unscoped index caused cross-domain confabulation; metadata boundaries made retrieval fit the operating context.",
  },
  {
    slug: "noc-fault-intelligence",
    title: "NOC Fault Intelligence Assistant",
    label: "Operations · Retrieval · Incident Response",
    evidence: "Professional experience · public-safe summary",
    role: "Alert correlation, historical retrieval, triage summaries, and operational safeguards",
    scope: "A network-operations assistant correlating live alerts with historical incidents and fault-resolution runbooks.",
    summary: "Structured triage summaries covering affected service, blast radius, likely root cause, and recommended first action.",
    outcome: "Reduced mean time to diagnose recurring fault classes by 34%.",
    stack: ["GPT-3", "Azure OpenAI", "FAISS", "FastAPI", "Python", "Elastic SIEM"],
    metrics: [["34%", "faster diagnosis"], ["5,000+", "incident records"], ["22 min", "bridge duration saved"]],
    problem: "On-call engineers lose time searching disconnected alerts, incident records, and runbooks during active faults.",
    decisions: ["Alert-to-history correlation", "Structured triage output", "Recent-incident time window", "Separate known-fault catalogue"],
    failure: "Stale remediation steps can mislead responders; time-windowed retrieval reduced the chance of surfacing obsolete guidance.",
  },
  {
    slug: "mortgage-document-classification",
    title: "Mortgage Document Classification",
    label: "BERT · Classification · MLflow",
    evidence: "Professional experience · public-safe summary",
    role: "Transformer modeling, confidence routing, evaluation, and API delivery",
    scope: "A confidence-gated BERT classification pipeline for mortgage-originations document categories with human review for ambiguous cases.",
    summary: "A model-first document workflow replacing brittle rules while preserving human oversight of low-confidence predictions.",
    outcome: "Reached 93.4% macro F1 and reduced analyst time per batch from 8.2 hours to 1.4 hours.",
    stack: ["BERT", "MLflow", "Flask", "PostgreSQL", "scikit-learn", "spaCy"],
    metrics: [["93.4%", "macro F1"], ["8.2 → 1.4", "hours per batch"], ["12", "document categories"]],
    problem: "Rules-based triage consumed analyst time and struggled with document variation, while ambiguous cases still required review.",
    decisions: ["Confidence-gated automation", "Human review tail", "Tracked model variants", "Compliance-approved REST deployment"],
    failure: "Automation without confidence routing would hide uncertainty; below-threshold documents remained in the analyst queue.",
  },
  {
    slug: "customer-sentiment-product-intelligence",
    title: "Customer Sentiment & Product Intelligence",
    label: "RoBERTa · NLP · Product Signals",
    evidence: "Professional experience · public-safe summary",
    role: "Sentiment modeling, product attribution, reporting, and integration",
    scope: "A daily sentiment pipeline combining transformer classification with product-category attribution and trend monitoring.",
    summary: "RoBERTa-based sentiment scoring across customer channels with category-level reporting and statistically significant change alerts.",
    outcome: "Processed 50,000+ records daily at 89.1% accuracy and surfaced signals that led to three product corrective actions.",
    stack: ["RoBERTa", "Python", "PostgreSQL", "Flask", "pandas", "spaCy"],
    metrics: [["89.1%", "sentiment accuracy"], ["50,000+", "daily records"], ["3", "corrective actions"]],
    problem: "Aggregate sentiment is less useful without product attribution, trend monitoring, and a path from signal to action.",
    decisions: ["Five-class sentiment scale", "NER-based product attribution", "Rolling-mean anomaly alerts", "Automated weekly reporting"],
    failure: "Lexicon baselines missed domain nuance; a RoBERTa model and category attribution produced more actionable product-level signals.",
  },
  {
    slug: "it-service-ticket-routing",
    title: "IT Service Ticket Routing",
    label: "BERT · APIs · Workflow Automation",
    evidence: "Professional experience · public-safe summary",
    role: "Intent classification, confidence routing, REST integration, and operations",
    scope: "A multi-class ticket-routing service for telecom and financial-services support queues with confidence-based manual escalation.",
    summary: "A BERT intent classifier integrated with enterprise ticketing systems to automate routing while protecting ambiguous multi-topic requests.",
    outcome: "Reduced misrouting from 18% to under 7% and cut mean time to first response by 22%.",
    stack: ["BERT", "MLflow", "Flask", "PostgreSQL", "scikit-learn", "REST API"],
    metrics: [["91.2%", "classification accuracy"], ["3,500+", "tickets per day"], ["31%", "fewer misroutes"]],
    problem: "Keyword rules misrouted multi-topic support tickets and delayed first response across high-volume service queues.",
    decisions: ["Multi-class intent model", "Confidence threshold routing", "REST ticketing integration", "Manual review for ambiguous cases"],
    failure: "Low-confidence and multi-topic requests were unsafe to auto-route; the confidence tail stayed visible to human triage.",
  },
] as const;

export const experience = [
  { company: "Tata Consultancy Services", role: "Generative AI Engineer", dates: "Sep 2026 — Present", location: "United States", mark: "TCS", logo: "/company-logos/tcs.svg", detail: "Architecting secure RAG and multi-step LLM services for regulated knowledge workflows, with access-aware retrieval, structured validation, evaluation gates, and auditable release controls.", transition: "Applied earlier NLP and AI application experience to the production controls required by enterprise GenAI.", highlights: ["Build retrieval pipelines with semantic chunking, metadata enrichment, hybrid search, reranking, grounded generation, and source attribution.", "Package controlled AI workflows as versioned FastAPI services with monitoring, rollback, and mandatory human-review boundaries; reduced documented research time from 45+ minutes to under 4 minutes in the public-safe workflow summary."] },
  { company: "Professional Services Organization", role: "Senior AI Engineer — AI/ML & Agentic Systems", dates: "Jan 2024 — Aug 2026", location: "United States", mark: "PSO", logo: "", detail: "Led production AI and agentic systems for audit and advisory workflows with bounded orchestration, retrieval, evaluation gates, human review, confidentiality controls, and operational observability.", transition: "Expanded from full-stack AI delivery into regulated document intelligence, agent state, model adaptation, evaluation, and recovery design.", highlights: ["Reduced manual document-review effort by 34% and reduced evidence-search time from about 40 minutes to under 4 minutes through grounded audit intelligence.", "Built 200+ domain evaluation cases, expanded coverage to 87%, blocked 11 regressions, improved task F1 from 0.74 to 0.91, and validated 10× traffic with Kubernetes autoscaling."] },
  { company: "BT Group", role: "Full Stack AI Engineer", dates: "Aug 2021 — Dec 2022", location: "United Kingdom", mark: "BT", logo: "/company-logos/bt.svg", detail: "Built retrieval-backed infrastructure guidance and natural-language automation capabilities supporting more than 100 engineers, with policy-aware templates and approval controls.", transition: "Connected model capability to usable services, retrieval, policy-aware templates, and developer workflows.", highlights: ["Improved infrastructure provisioning speed by 60% while reducing template errors by 74% through validated natural-language workflows.", "Combined curated engineering documentation, source-aware responses, policy checks, and human approval in a developer-facing assistant."] },
  { company: "Tech Mahindra", role: "Application Development Engineer — AI/ML Practice", dates: "Nov 2018 — Dec 2019", location: "India", mark: "TM", logo: "/company-logos/tech-mahindra.svg", detail: "Developed BERT and RoBERTa-based document classification, sentiment analysis, and request-routing capabilities for enterprise applications.", transition: "Started with measurable transformer-based NLP features and the application contracts around them.", highlights: ["Built a BERT document classifier reaching 93.4% macro F1 and reproducible training, error-analysis, threshold-tuning, and regression workflows.", "Delivered model predictions through stable REST interfaces, reducing misrouted tickets by 31% with versioned MLflow patterns."] },
] as const;

export const education = [
  ["Master of Science, Computer Science", "Campbellsville University", "2023 — 2024", "CU", "https://day1cptuniversities.com/hs-fs/hubfs/17-Apr-18-2024-12-22-11-3497-AM.png?height=600&name=17-Apr-18-2024-12-22-11-3497-AM.png&width=600"],
  ["Master of Science, Information Technology Security", "Nottingham Trent University", "Jan 2020 — Aug 2021", "NTU", "https://upload.wikimedia.org/wikipedia/commons/f/f5/Logo_Nottingham_Trent_University.svg"],
  ["Bachelor of Technology, Electronics & Computer Science Engineering", "KL University", "2014 — 2018", "KL", "https://image.pngaaa.com/701/4725701-middle.png"],
] as const;

export const skillGroups = [
  ["Models & Orchestration", ["GPT-4o", "Azure OpenAI", "Llama 3", "Claude 3.5", "LoRA / QLoRA", "Prompt engineering", "Tool calling", "Structured outputs"]],
  ["Retrieval", ["Hybrid search", "Cross-encoder reranking", "Metadata filtering", "Source attribution", "Pinecone", "FAISS", "ChromaDB", "Weaviate"]],
  ["Evaluation", ["RAGAS", "DeepEval", "200+ curated test sets", "Faithfulness", "Answer relevancy", "Regression suites", "Red teaming"]],
  ["Platform", ["Python", "FastAPI", "REST APIs", "SQL", "Docker", "Kubernetes HPA", "Azure", "Databricks", "PySpark", "MLflow"]],
  ["Security", ["Prompt injection defense", "PII detection and redaction", "Access-aware retrieval", "Tool authorization", "Output validation", "Audit logging", "Content controls"]],
  ["Operations", ["Latency and token metrics", "Traceability", "Version tracking", "Monitoring", "Feedback loops", "Failure recovery"]],
] as const;

export const certifications = [
  ["Microsoft Certified: Azure AI Engineer Associate", "AI-102", "2025"],
  ["Certified Kubernetes Application Developer", "CKAD", "2023"],
  ["Fine-tuning Large Language Models", "DeepLearning.AI", "2024"],
  ["LangChain for LLM Application Development", "DeepLearning.AI", "2024"],
  ["RAGAS & LLM Evaluation Practitioner Workshop", "RAGAS / deepeval", "2024"],
  ["Building Agentic RAG with LlamaIndex", "DeepLearning.AI", "2025"],
] as const;

export const fieldNotes = [
  { slug: "evaluating-faithfulness-in-rag", type: "Evaluation note", title: "How to evaluate faithfulness in RAG systems", summary: "A practical way to separate retrieval coverage, supported claims, adversarial cases, and release decisions.", tags: ["RAG", "Evaluation"], href: "/notes/evaluating-faithfulness-in-rag", publishedAt: "2026-09-14" },
  { slug: "release-gates-for-llm-systems", type: "Decision note", title: "Release gates for LLM systems", summary: "Why quality, security, latency, and rollback evidence should travel together before an AI feature reaches production.", tags: ["Evaluation", "Operations"], href: "/notes/release-gates-for-llm-systems", publishedAt: "2026-09-09" },
  { slug: "bounded-agents-over-open-loops", type: "Architecture note", title: "When a bounded workflow beats an autonomous loop", summary: "A practical decision rule for choosing explicit states, scoped tools, approval gates, and recovery paths.", tags: ["Agents", "Control"], href: "/notes/bounded-agents-over-open-loops", publishedAt: "2026-09-04" },
  { slug: "retrieval-is-a-security-boundary", type: "Security note", title: "Retrieved text is evidence—not authority", summary: "How to keep malicious or irrelevant instructions inside retrieved content from becoming executable model behavior.", tags: ["RAG", "Security"], href: "/notes/retrieval-is-a-security-boundary", publishedAt: "2026-08-29" },
] as const;

export const assistantAnswers = [
  { match: ["project", "built", "worked"], title: "Projects", text: "Lokesh’s resume documents 11 named projects across regulatory intelligence, audit intelligence, due diligence, LLM evaluation, model adaptation, infrastructure provisioning, network operations, and applied NLP.", sources: ["Projects / Case studies", "Experience"] },
  { match: ["azure", "openai", "cloud"], title: "Azure OpenAI", text: "Azure OpenAI appears across the regulatory intelligence, audit intelligence, due-diligence, infrastructure, and evaluation workflows, behind server-side boundaries with policy checks and traceable outputs.", sources: ["Architecture / Model gateway", "Projects / Case studies"] },
  { match: ["security", "prompt", "injection", "pii"], title: "LLM security", text: "His security approach treats user input, retrieved documents, and tool responses as separate trust domains, with injection detection, PII handling, scoped authorization, output validation, and audit logs.", sources: ["Security Lab", "Architecture / Trust boundaries"] },
  { match: ["experience", "career", "company"], title: "Experience", text: "Lokesh’s progression spans transformer-based NLP, retrieval-backed infrastructure and network operations, audit and agentic systems in professional services, and current regulated GenAI engineering.", sources: ["Experience", "About / Career map"] },
  { match: ["evaluation", "metrics", "quality", "hallucination"], title: "Evaluation", text: "The portfolio demonstrates task-specific test suites across retrieval quality, faithfulness, answer relevance, latency, token use, guardrail performance, and failure recovery.", sources: ["Lab / Evaluation dashboard", "Architecture / Validation"] },
] as const;
